### ISSUE TITLE
npm start is error? why ?

### ISSUE THREAD

**Issue by jang-git** [sealtalk/sealtalk-desktop#4]
App threw an error when running Error: Dynamic Linking Error: dlopen(node_modules/screenshot.framework/screenshot, 1): image not found
    at new DynamicLibrary (/Users/Jang/Downloads/sealtalk-desktop/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.dlopen (/Users/Jang/Downloads/sealtalk-desktop/node_modules/nodobjc/lib/core.js:99:12)
    at Object.importFramework (/Users/Jang/Downloads/sealtalk-desktop/node_modules/nodobjc/lib/import.js:308:60)
    at Function.framework (/Users/Jang/Downloads/sealtalk-desktop/node_modules/nodobjc/lib/index.js:225:18)
    at Object.<anonymous> (/Users/Jang/Downloads/sealtalk-desktop/main.js:69:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by raytong** [comment]
same here ,can anyone resolve it?

**Comment by shuise** [comment]
please check the “特殊说明” ,sometimes app should redefine.

**Comment by YongHao0** [comment]
此项目已废弃, 新版请参考: https://www.rongcloud.cn/docs/desktop
