### ISSUE TITLE
制作安装包 错误

### ISSUE THREAD

**Issue by raytong** [sealtalk/sealtalk-desktop#5]
npm start 正常，打包正常，但是 制作安装包的时候 出现如下错误：
Error: The module '/Users/ray/Development/instantMessager/desktop/eaim-desktop/node_modules/macos-alias/build/Release/volume.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ray/Development/instantMessager/desktop/eaim-desktop/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ray/Development/instantMessager/desktop/eaim-desktop/node_modules/macos-alias/index.js:1:18)
    at Module._compile (module.js:571:32)

试过 npm rebuild，electron 官方的方法， electron-rebuild 都没有好用

**Comment by YongHao0** [comment]
此项目已废弃, 新版请参考: https://www.rongcloud.cn/docs/desktop
